# Generated by Django 4.2.1 on 2023-12-13 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('poster', models.ImageField(upload_to='game_posters/')),
                ('num_seasons', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('poster', models.ImageField(upload_to='season_posters/')),
                ('memory_wall', models.ImageField(upload_to='memory_walls/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='games.game')),
                ('players', models.ManyToManyField(related_name='seasons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
