# Generated by Django 4.2.1 on 2023-12-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='memory_wall',
            field=models.ImageField(null=True, upload_to='memory_walls/'),
        ),
    ]
