# Generated by Django 4.2.1 on 2023-12-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_customuser_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='points',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
